### ISSUE TITLE
Some questions about the version of the code used

### ISSUE THREAD

**Issue by cwbf** [StefannyEscobar/InverseHeat_NN#1]
Hello, I am a student, currently studying neural networks and heat conduction problems.When I run the code, it reports a version error，Can you tell me the installed version information like tensorflow, fenics and pip list used in code ？Thanks

**Comment by cwbf** [comment]
when I run this code, the pycharm report these information:

UserWarning: h5py is running against HDF5 1.10.0 when it was built against 1.10.2, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Solving linear variational problem.
Después de la optimización:
Valor optimizado de d: 200.0
Loading the trained neural network model...
Traceback (most recent call last):
  File "/mnt/d/code/InverseHeat_NN-main/main.py", line 115, in <module>
    model = tf.keras.models.load_model('trained_model')
  File "/home/wang1804/pinn/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 218, in load_model
    f = h5py.File(filepath, mode='r')
  File "/home/wang1804/pinn/lib/python3.6/site-packages/h5py/_hl/files.py", line 311, in __init__
    fapl = make_fapl(driver, libver, **kwds)
  File "/home/wang1804/pinn/lib/python3.6/site-packages/h5py/_hl/files.py", line 102, in make_fapl
    plist.set_libver_bounds(low, high)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5p.pyx", line 1070, in h5py.h5p.PropFAID.set_libver_bounds
ValueError: Invalid high library version bound (invalid high library version bound)
RUNNING THE L-BFGS-B CODE

Machine precision = 2.220D-16
 N =          121     M =           10

At X0       121 variables are exactly at the bounds

At iterate    0    f=  1.12928D-09    |proj g|=  3.52950D-13

At iterate    1    f=  1.12928D-09    |proj g|=  3.52950D-13

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value


   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
  121      1      2      1     0     0   3.530D-13   1.129D-09
  F =  1.12927910159083373E-009

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             







**This is my pip list：**
absl-py (1.4.0)
asn1crypto (0.24.0)
astor (0.8.1)
attrs (17.4.0)
Automat (0.6.0)
blinker (1.4)
cached-property (2.0)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
cloud-init (23.1.2)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
cryptography (2.1.4)
cycler (0.10.0)
dataclasses (0.8)
distro-info (0.18ubuntu0.18.04.1)
dolfin-adjoint (2019.1.0)
fenics-dijitso (2019.2.0.dev0)
fenics-dolfin (2019.2.0.dev0)
fenics-ffc (2019.2.0.dev0)
fenics-fiat (2019.2.0.dev0)
fenics-ufl (2021.1.0)
gast (0.6.0)
grpcio (1.48.2)
h5py (2.8.0)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.6)
importlib-metadata (4.8.3)
incremental (16.10.1)
Jinja2 (2.10)
jsonpatch (1.16)
jsonpointer (1.10)
jsonschema (2.6.0)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.2)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
Markdown (3.3.7)
MarkupSafe (1.0)
matplotlib (2.1.1)
mpi4py (2.0.0)
mpmath (1.0.0)
mshr (2019.2.0.dev0)
netifaces (0.10.4)
numpy (1.14.5)
oauthlib (2.0.6)
olefile (0.45.1)
PAM (0.4.2)
petsc4py (3.7.0)
pexpect (4.2.1)
Pillow (5.1.0)
pip (9.0.1)
pkg-resources (0.0.0)
pkgconfig (1.3.1)
ply (3.11)
protobuf (3.6.1)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pybind11 (2.2.3)
pycrypto (2.6.1)
pygobject (3.26.1)
PyJWT (1.5.3)
pyOpenSSL (17.5.0)
pyparsing (2.2.0)
pyserial (3.4)
python-apt (1.6.6)
python-dateutil (2.6.1)
python-debian (0.1.32)
pytz (2018.3)
pyxdg (0.25)
PyYAML (3.12)
requests (2.18.4)
requests-unixsocket (0.1.5)
scipy (1.5.4)
SecretStorage (2.3.1)
service-identity (16.0.0)
setuptools (39.0.1)
six (1.16.0)
slepc4py (3.7.0)
sos (4.4)
ssh-import-id (5.7)
sympy (1.1.1)
systemd-python (234)
tensorboard (1.10.0)
tensorflow (1.10.0)
tensorflow-probability (0.5.0)
termcolor (1.1.0)
Twisted (17.9.0)
typing-extensions (4.1.1)
ubuntu-advantage-tools (8001)
ufw (0.36)
unattended-upgrades (0.1)
urllib3 (1.22)
Werkzeug (2.0.3)
wheel (0.30.0)
zipp (3.6.0)
zope.interface (4.3.2)
